version: '3.8'
services:
  app:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    container_name: zones-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    volumes:
      - ./Front-End/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  nginx:
    image: nginx:alpine
    container_name: zones-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Front-End/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Front-End/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
